// trackList.js - All tracks organized by category
var trackLibrary = {
        "ES LoFi": [ 
            { title: "Aesthetic Echoes in Motion", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Aesthetic_Echoes_in_Motion_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:37" },
            { title: "Break It Down", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Break_It_Down_-_Dyalla.wav?raw=true", category: "LoFi", duration: "2:46" },
            { title: "Coffee in My Garden", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Coffee_in_My_Garden_-_baegel.wav?raw=true", category: "LoFi", duration: "2:30" },
            { title: "Daydreaming About You While Drinking a Cup of Tea", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Daydreaming_About_You_While_Drinking_a_Cup_of_Tea_-_baegel.wav?raw=true", category: "LoFi", duration: "2:03" },
            { title: "Distractions", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Distractions_-_Timothy_Infinite.wav?raw=true", category: "LoFi", duration: "2:15" },
            { title: "Drops", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Drops_-_HATAMITSUNAMI.wav?raw=true", category: "LoFi", duration: "2:57" },
            { title: "Earth Oak", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Earth_Oak_-_Guustavv.wav?raw=true", category: "LoFi", duration: "2:58" },
            { title: "Find Me Again", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Find_Me_Again_-_Mizlo.wav?raw=true", category: "LoFi", duration: "2:11" },
            { title: "Finetuned Fiesta", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Finetuned_Fiesta_-_Dusty_Decks.wav?raw=true", category: "LoFi", duration: "2:39" },
            { title: "For the Feeling", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_For_the_Feeling_-_Mizlo.wav?raw=true", category: "LoFi", duration: "2:09" },
            { title: "Homesick", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Homesick_-_DonVayei.wav?raw=true", category: "LoFi", duration: "2:10" },
            { title: "I Got a Bad Habit (Instrumental Version)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_I_Got_a_Bad_Habit_Instrumental_Version_-_Nyck_Caution.wav?raw=true", category: "LoFi", duration: "2:03" },
            { title: "I Have a Crush on You", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_I_Have_a_Crush_on_You_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "3:04" },
            { title: "Im a Dawg", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Im_a_Dawg_-_Curli_Loxx.wav?raw=true", category: "LoFi", duration: "2:35" },
            { title: "I'm a Fool (for U)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Im_a_Fool_for_U_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:53" },
            { title: "It Hasn't Been Cloudy Since We Met", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_It_Hasnt_Been_Cloudy_Since_We_Met_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:55" },
            { title: "Jacuzzi", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Jacuzzi_-_Jobii.wav?raw=true", category: "LoFi", duration: "2:07" },
            { title: "Lap of Luxury", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Lap_of_Luxury_-_Auxjack.wav?raw=true", category: "LoFi", duration: "2:30" },
            { title: "Mango Fizz", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Mango_Fizz_-_Jobii.wav?raw=true", category: "LoFi", duration: "2:26" },
            { title: "Maybe L8er", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Maybe_L8er_-_Rocket_Jr.wav?raw=true", category: "LoFi", duration: "3:07" },
            { title: "Midnight in Mono", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Midnight_in_Mono_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "3:32" },
            { title: "Morning Coffee", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Morning_Coffee_-_Dyalla.wav?raw=true", category: "LoFi", duration: "2:01" },
            { title: "Multidimensional", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Multidimensional_-_Sarah_the_Illstrumentalist.wav?raw=true", category: "LoFi", duration: "2:30" },
            { title: "Nested Above", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Nested_Above_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:04" },
            { title: "Odd Sensibility", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Odd_Sensibility_-_Jules_Gaia.wav?raw=true", category: "LoFi", duration: "2:29" },
            { title: "Old School Soul", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Old_School_Soul_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "3:03" },
            { title: "overture", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_overture_-_dozeoff.wav?raw=true", category: "LoFi", duration: "2:23" },
            { title: "Saturday Reset", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Saturday_Reset_-_Sarah_the_Illstrumentalist.wav?raw=true", category: "LoFi", duration: "2:34" },
            { title: "Sauts Modiques", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Sauts_Modiques_-_Dusty_Decks.wav?raw=true", category: "LoFi", duration: "2:32" },
            { title: "Seahorsing", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Seahorsing_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "3:01" },
            { title: "Seasonal League", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Seasonal_League_-_Dusty_Decks.wav?raw=true", category: "LoFi", duration: "2:59" },
            { title: "Soft Pine", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Soft_Pine_-_Jobii.wav?raw=true", category: "LoFi", duration: "2:16" },
            { title: "Sonic Raindrops", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Sonic_Raindrops_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:50" },
            { title: "Spent a Whole Day in My Head", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Spent_a_Whole_Day_in_My_Head_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "2:42" },
            { title: "Squeeze", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Squeeze_-_Jobii.wav?raw=true", category: "LoFi", duration: "2:09" },
            { title: "Subtle Movement", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Subtle_Movement_-_Loyae.wav?raw=true", category: "LoFi", duration: "2:49" },
            { title: "Sunrise to Sunset", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Sunrise_to_Sunset_-_Rebecca_Mardal.wav?raw=true", category: "LoFi", duration: "3:25" },
            { title: "Tapestry Tincture", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Tapestry_Tincture_-_Guustavv.wav?raw=true", category: "LoFi", duration: "2:06" },
            { title: "The Happiest Moment", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_The_Happiest_Moment_-_Lukas_Got_Lucky.wav?raw=true", category: "LoFi", duration: "2:30" },
            { title: "This Makes Everything Better", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_This_Makes_Everything_Better_-_Sarah_the_Illstrumentalist.wav?raw=true", category: "LoFi", duration: "2:05" },
            { title: "To and From", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_To_and_From_-_DonVayei.wav?raw=true", category: "LoFi", duration: "2:07" },
            { title: "Tokyo Tuesday", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Tokyo_Tuesday_-_Guustavv.wav?raw=true", category: "LoFi", duration: "2:24" },
            { title: "Victory Laps", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ES_Victory_Laps_-_Dusty_Decks.wav?raw=true", category: "LoFi", duration: "2:25" }
        ],
        "AL LoFi": [
            { title: "Raindrops", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/ariel_shalom_-_raindrops.wav?raw=true", category: "LoFi", duration: "1:55" },
            { title: "Bubble Bath", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/aves_-_bubble_bath.wav?raw=true", category: "LoFi", duration: "3:12" },
            { title: "Coffee Stop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/aves_-_coffee_stop.wav?raw=true", category: "LoFi", duration: "2:19" },
            { title: "River Banks", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/dor_hadad_-_river_banks.wav?raw=true", category: "LoFi", duration: "2:47" },
            { title: "The Living Room", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/flint_-_the_living_room.wav?raw=true", category: "LoFi", duration: "3:08" },
            { title: "A Part of Me", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/ikoliks_-_a_part_of_me.wav?raw=true", category: "LoFi", duration: "1:59" },
            { title: "Busi", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/jimit_-_busi.wav?raw=true", category: "LoFi", duration: "3:09" },
            { title: "Augmaster", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/jozeque_-_augmaster.wav?raw=true", category: "LoFi", duration: "2:35" },
            { title: "Cup O Tea", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/lalinea_-_cup_o_tea.wav?raw=true", category: "LoFi", duration: "2:47" },
            { title: "Come Over", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/novembers_-_come_over.wav?raw=true", category: "LoFi", duration: "2:35" },
            { title: "Zircon", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/ottom_-_zircon.wav?raw=true", category: "LoFi", duration: "1:53" },
            { title: "Magic Hour", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/samurai_royal_-_magic_hour.wav?raw=true", category: "LoFi", duration: "2:45" },
            { title: "Pink Desert", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/samurai_royal_-_pink_desert.wav?raw=true", category: "LoFi", duration: "2:19" },
            { title: "Forgive", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/sero_-_forgive.wav?raw=true", category: "LoFi", duration: "2:54" },
            { title: "A Trip", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/sig_howler_-_a_trip.wav?raw=true", category: "LoFi", duration: "2:37" },
            { title: "Sunchilling", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/vicate_-_sunchilling.wav?raw=true", category: "LoFi", duration: "2:26" },
            { title: "Ocean Hued", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/wav_two_-_ocean_hued.wav?raw=true", category: "LoFi", duration: "2:56" },
            { title: "Dreams", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/artlist_lofi/woolfson_-_dreams.wav?raw=true", category: "LoFi", duration: "1:55" }
        ], 
        "LoFi": [
            { title: "1999 Bedroom Beats", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/1999_bedroom_beats.wav?raw=true", category: "LoFi", duration: "2:21" },
            { title: "Cafe con Leche Beats", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/cafe_con_leche_beats.wav?raw=true", category: "LoFi", duration: "2:14" },
            { title: "Cafe Window Rain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/cafe_window_rain.wav?raw=true", category: "LoFi", duration: "2:39" },
            { title: "Cat Cafe Boogie", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/cat_cafe_boogie.wav?raw=true", category: "LoFi", duration: "1:50" },
            { title: "Diner Booth Dreams", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/diner_booth_dreams.WAV?raw=true", category: "LoFi", duration: "2:03" },
            { title: "Fading Streetlights", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/fading_streetlights.wav?raw=true", category: "LoFi", duration: "1:47" },
            { title: "Falling Through Hourglasses", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/falling_through_hourglasses.wav?raw=true", category: "LoFi", duration: "1:58" },
            { title: "Fingers on Dusty Keys", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/fingers_on_dusty_keys.wav?raw=true", category: "LoFi", duration: "2:14" },
            { title: "Five A.M. Jazz Club", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/five_am_jazz_club.wav?raw=true", category: "LoFi", duration: "2:01" },
            { title: "Fretboard Dreams", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/fretboard_dreams.wav?raw=true", category: "LoFi", duration: "1:30" },
            { title: "Half-Speed Heartbeats", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/half_speed_heartbeats.wav?raw=true", category: "LoFi", duration: "2:32" },
            { title: "Honey Drip Melodies", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/honey_drip_melodies.wav?raw=true", category: "LoFi", duration: "2:50" },
            { title: "Ice Melting in Slow Motion", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/ice_melting_in_slow_motion.wav?raw=true", category: "LoFi", duration: "1:47" },
            { title: "Koi Pond Calculus", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/koi_pond_calculus.wav?raw=true", category: "LoFi", duration: "2:34" },
            { title: "Like Water in Dreams", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/like_water_in_dreams.wav?raw=true", category: "LoFi", duration: "3:03" },
            { title: "Low-Key Hustle", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/low_key_hustle.wav?raw=true", category: "LoFi", duration: "1:28" },
            { title: "Margin Notes at 2 AM", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/margin_notes_at_2_am.wav?raw=true", category: "LoFi", duration: "2:14" },
            { title: "Neon Bicycle", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/neon_bicycle.wav?raw=true", category: "LoFi", duration: "3:25" },
            { title: "Nylon String Sunset", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/nylon_string_sunset.wav?raw=true", category: "LoFi", duration: "2:18" },
            { title: "Pencil Marks on Sheet Music", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/pencil_marks_on_sheet_music.wav?raw=true", category: "LoFi", duration: "1:37" },
            { title: "Pixelated Picnic", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/pixelated_picnic.wav?raw=true", category: "LoFi", duration: "2:08" },
            { title: "Popsicle Summer", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/popsicle_summer.wav?raw=true", category: "LoFi", duration: "2:15" },
            { title: "Smoke Rings in B-Flat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/smoke_rings_in_b_flat.wav?raw=true", category: "LoFi", duration: "1:40" },
            { title: "Sneaker Scuff Symphony", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/sneaker_scuff_symphony.wav?raw=true", category: "LoFi", duration: "1:46" },
            { title: "Subway Graffiti Heartbeat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/subway_graffiti_heartbeat.wav?raw=true", category: "LoFi", duration: "2:30" },
            { title: "Sunburn Serenade", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/sunburn_serenade.wav?raw=true", category: "LoFi", duration: "1:57" },
            { title: "Taxi Window Views", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/taxi_window_views.wav?raw=true", category: "LoFi", duration: "3:13" },
            { title: "The Art of Slowing Down", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/the_art_of_slowing_down.wav?raw=true", category: "LoFi", duration: "2:26" },
            { title: "The Lake at 4 AM", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/the_lake_at_4_am.wav?raw=true", category: "LoFi", duration: "1:45" },
            { title: "The Last Candle Burns", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/the_last_candle_burns.wav?raw=true", category: "LoFi", duration: "2:56" },
            { title: "Tickets to Nowhere", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/tickets_to_nowhere.wav?raw=true", category: "LoFi", duration: "2:09" },
            { title: "Vinyl Hustle", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/vinyl_hustle.wav?raw=true", category: "LoFi", duration: "2:23" },
            { title: "Warm Blanket Thoughts", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/lofi/warm_blanket_thoughts.wav?raw=true", category: "LoFi", duration: "1:15" }
        ], 
        "Background Music": [
            { title: "A Thousand Quiet Thoughts", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/a_thousand_quiet_thoughts.wav?raw=true", category: "Background Music", duration: "8:30" },
            { title: "Bubbles in the Sunshine", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/bubbles_in_the_sunshine.wav?raw=true", category: "Background Music", duration: "2:13" },
            { title: "Dawn in the Misty Pines", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dawn_in_the_misty_pines.wav?raw=true", category: "Background Music", duration: "2:11" },
            { title: "Floating in the Stratosphere", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/floating_in_the_stratosphere.wav?raw=true", category: "Background Music", duration: "2:28" },
            { title: "Midnight in the Neon Glow", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/midnight_in_the_neon_glow.wav?raw=true", category: "Background Music", duration: "2:27" },
            { title: "Moon Milk Lullaby", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/moon_milk_lullaby.wav?raw=true", category: "Background Music", duration: "7:11" },
            { title: "Moss-Covered Memories", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/moss_covered_memories.wav?raw=true", category: "Background Music", duration: "1:36" },
            { title: "Nebula Lullaby", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/nebula_lullaby.wav?raw=true", category: "Background Music", duration: "3:02" },
            { title: "Oblivion's Gentle Pull", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/oblivions_gentle_pull.wav?raw=true", category: "Background Music", duration: "3:12" },
            { title: "Radio Waves from Andromeda", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/radio_waves_from_andromeda.wav?raw=true", category: "Background Music", duration: "4:16" },
            { title: "Silent Echo Chamber (guitar)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/silent_echo_chamber_guitar.wav?raw=true", category: "Background Music", duration: "3:09" },
            { title: "Silent Echo Chamber", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/silent_echo_chamber.wav?raw=true", category: "Background Music", duration: "3:09" },
            { title: "Sunny Side Upbeat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/sunny_side_upbeat.wav?raw=true", category: "Background Music", duration: "2:02" },
            { title: "The Library of Forgotten Sounds", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/the_library_of_forgotten_sounds.wav?raw=true", category: "Background Music", duration: "2:42" },
            { title: "The Quiet Side of the Moon", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/the_quiet_side_of_the_moon.wav?raw=true", category: "Background Music", duration: "4:14" },
            { title: "The Space Between Heartbeats", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/the_space_between_heartbeats.wav?raw=true", category: "Background Music", duration: "3:40" },
            { title: "Time Dissolves in Water", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/time_dissolves_in_water.wav?raw=true", category: "Background Music", duration: "2:04" },
            { title: "Whispers of the Aurora", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/background/whispers_of_the_aurora.wav?raw=true", category: "Background Music", duration: "2:36" }
        ],
        "Coding Mix": [
            { title: "VHS Waterfalls", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/coding_mix/raz_stamper_-_vhs_waterfalls.wav?raw=true", category: "Coding Mix", duration: "2:36" },
            { title: "Light Rails", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/coding_mix/lucky_sound_-_light_rails.wav?raw=true", category: "Coding Mix", duration: "2:25" },
            { title: "Breath of Autumn", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/coding_mix/vladislav_kurnikov_-_breath_of_autumn.wav?raw=true", category: "Coding Mix", duration: "3:05" }
        ],
        "Meditation": [
            { title: "Mist Over the Lotus Pond", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/mist_over_the_lotus_pond.wav?raw=true", category: "Meditation", duration: "19:54" },
            { title: "Journey Through the Chakras", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/journey_through_the_chakras.wav?raw=true", category: "Meditation", duration: "11:12" },
            { title: "Moonlit Path to Inner Peace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/moonlit_path_to_inner_peace.wav?raw=true", category: "Meditation", duration: "8:30" },
            { title: "Starlight Meditation", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/starlight_meditation.wav?raw=true", category: "Meditation", duration: "8:29" },
            { title: "Breath of Stillness", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/breath_of_stillness.wav?raw=true", category: "Meditation", duration: "8:11" },
            { title: "Shaman's Dreamcatcher", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/shaman's_dreamcatcher.wav?raw=true", category: "Meditation", duration: "7:49" },
            { title: "Zen Garden at Dusk", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/zen_garden_at_dusk.wav?raw=true", category: "Meditation", duration: "7:06" },
            { title: "Third Eye Awakens", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/third_eye_awakens.wav?raw=true", category: "Meditation", duration: "6:47" },
            { title: "Reiki Waves of Serenity", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/reiki_waves_of_serenity.wav?raw=true", category: "Meditation", duration: "6:05" },
            { title: "Floating Among the Clouds", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/floating_among_the_clouds.wav?raw=true", category: "Meditation", duration: "5:41" },
            { title: "The Universe Sings in Solitude", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/the_universe_sings_in_solitude.wav?raw=true", category: "Meditation", duration: "5:20" },
            { title: "Ashot Danielyan", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/ashot_danielyan.wav?raw=true", category: "Meditation", duration: "5:14" },
            { title: "The Sound of Silence", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/the_sound_of_silence.wav?raw=true", category: "Meditation", duration: "5:12" },
            { title: "Nebula's Embrace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/nebulas_embrace.wav?raw=true", category: "Meditation", duration: "3:45" },
            { title: "Rainfall on Bamboo Leaves", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/rainfall_on_bamboo_leaves.wav?raw=true", category: "Meditation", duration: "3:12" },
            { title: "Glacial Winds of Tibet", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/glacial_winds_of_tibet.wav?raw=true", category: "Meditation", duration: "3:12" },
            { title: "Sacred Chant", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/sacred_chant.wav?raw=true", category: "Meditation", duration: "3:10" },
            { title: "Stardust Lullaby", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/stardust_lullaby.wav?raw=true", category: "Meditation", duration: "3:09" },
            { title: "Stardust Lullaby (No Acoustic Guitar)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/stardust_lullaby_no_acoustic_guitar.wav?raw=true", category: "Meditation", duration: "3:09" },
            { title: "Sunrise Over Rice Fields", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/sunrise_over_rice_fields.wav?raw=true", category: "Meditation", duration: "2:34" },
            { title: "The Monk's Prayer at Dawn", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/the_monks_prayer_at_dawn.wav?raw=true", category: "Meditation", duration: "2:16" },
            { title: "Beneath the Bodhi Tree", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/beneath_the_bodhi_tree.wav?raw=true", category: "Meditation", duration: "2:14" },
            { title: "Paradise - Vincent Vega", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/meditation/paradise_vincent_vega.wav?raw=true", category: "Meditation", duration: "2:09" }
        ],
        "Dark": [
            { title: "Lunar Reverie", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/ES_Lunar_Reverie_-_Lucas_Pittman.wav?raw=true", category: "Dark", duration: "5:04" },
            { title: "Kanjo", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/jozeque_-_kanjo.wav?raw=true", category: "Dark", duration: "2:55" },
            { title: "Morning Caffe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/jozeque_-_morning_caffe.wav?raw=true", category: "Dark", duration: "2:35" },
            { title: "Slumber", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/michael_drake_-_slumber.wav?raw=true", category: "Dark", duration: "2:46" },
            { title: "Empire", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/oliver_michael_-_empire.wav?raw=true", category: "Dark", duration: "4:30" },
            { title: "Deserved", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/scro_-_deserved.wav?raw=true", category: "Dark", duration: "3:11" },
            { title: "Forest Sun", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/dark/sero_-_forest_sun.wav?raw=true", category: "Dark", duration: "3:18" }
        ],
        "Classical": [
            { title: "Bach", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/bach.wav?raw=true", category: "Classical", duration: "4:36" },
            { title: "Canon in D", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/canon_in_d.wav?raw=true", category: "Classical", duration: "4:36" },
            { title: "Mozart Nachtmusik Serenade", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/mozart_nachtmusik_serenade.wav?raw=true", category: "Classical", duration: "3:01" },
            { title: "Mozart Requiem Lacrimos (No Vocals)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/mozart_requiem_lacrimos_no_vocals.wav?raw=true", category: "Classical", duration: "2:56" },
            { title: "Mozart Requiem Lacrimosa", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/mozart_requiem_lacrimosa.wav?raw=true", category: "Classical", duration: "2:56" },
            { title: "Mozart Sonata in C", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/classical/mozart_sonata_in_c.wav?raw=true", category: "Classical", duration: "2:22" }
        ],
        "Choir": [
            { title: "Cathedral", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/cathedral.wav?raw=true", category: "Choir", duration: "1:25" },
            { title: "Celestial Church Choir", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/celestial_church-choir.wav?raw=true", category: "Choir", duration: "1:26" },
            { title: "Choir", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/choir.wav?raw=true", category: "Choir", duration: "2:13" },
            { title: "Era of Majesty", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/era_of_majesty.wav?raw=true", category: "Choir", duration: "2:11" },
            { title: "Gregorian Chants", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/gregorian_chants.wav?raw=true", category: "Choir", duration: "2:46" },
            { title: "Medieval Female Choir", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/medieval_female_choir.wav?raw=true", category: "Choir", duration: "4:32" },
            { title: "Neoclassical Chorals, op. 3, Fading Voices", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/choir/neoclassical_chorals.wav?raw=true", category: "Choir", duration: "6:48" }
        ],
        "Fantasy": [
            { title: "A Klezmer Melancholy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/a_klezmer_melancholy.wav?raw=true", category: "Fantasy", duration: "3:08" },
            { title: "Ancient Athens", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/ancient_athens.wav?raw=true", category: "Fantasy", duration: "3:31" },
            { title: "Ancient Sumer", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/ancient_sumer.wav?raw=true", category: "Fantasy", duration: "2:46" },
            { title: "Celtic Harp Fantasy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/celtic_harp_fantasy.wav?raw=true", category: "Fantasy", duration: "4:52" },
            { title: "Magic", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/magic.wav?raw=true", category: "Fantasy", duration: "2:31" },
            { title: "The Blood-Stained Harp of Voran", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/the_blood-stained_harp_of_voran.wav?raw=true", category: "Fantasy", duration: "1:53" },
            { title: "The Fairy King's Lament", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/the_fairy_kings_lament.wav?raw=true", category: "Fantasy", duration: "2:05" },
            { title: "The Sorcerer's Nocturne", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/Fantasy/the_sorcere's_nocturne.wav?raw=true", category: "Fantasy", duration: "1:36" }
        ],
        "Vocals": [
            { title: "Cinematic Beauty", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/cinematic_beauty.wav?raw=true", category: "Vocals", duration: "2:30" },
            { title: "Cinematic Beauty (No Percussion)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/cinematic_beauty_no_percussion.wav?raw=true", category: "Vocals", duration: "2:30" },
            { title: "Dies Irae Requiem (Female Vocal)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/dies_irae_requiem_female_vocal.wav?raw=true", category: "Vocals", duration: "1:58" },
            { title: "Dies Irae Requiem (Female Vocal Solo)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/dies_irae_requiem_female_vocal_solo.wav?raw=true", category: "Vocals", duration: "1:58" },
            { title: "African Female Vocals", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/african_female_vocals.wav?raw=true", category: "Vocals", duration: "2:29" },
            { title: "Ethereal Magic (Female Vocals)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/ethereal_magic_female_vocals_wav.wav?raw=true", category: "Vocals", duration: "1:37" },
            { title: "Female Opera Vocal", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/female_opera_vocal.wav?raw=true", category: "Vocals", duration: "2:45" },
            { title: "Morning Angels", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/morning_angels.wav?raw=true", category: "Vocals", duration: "0:49" },
            { title: "Sad A Capella (Female Vocals)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/sad_a_capella_female_vocals.wav?raw=true", category: "Vocals", duration: "2:16" },
            { title: "Uplifting Vocals", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/vocals/uplifting_vocals.wav?raw=true", category: "Vocals", duration: "2:11" }
        ],
        "Piano": [
            { title: "Bach Fugue No. 21", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/bach_fugue_no_21.wav?raw=true", category: "Piano", duration: "1:44" },
            { title: "Blue Notes & Bourbon Jazz", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/blue_notes_&_bourbon_jazz.wav?raw=true", category: "Piano", duration: "2:14" },
            { title: "Chopin Nocturne", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/chopin_nocturne.wav?raw=true", category: "Piano", duration: "4:06" },
            { title: "Clair de Lune", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/clair_de_lune.wav?raw=true", category: "Piano", duration: "4:49" },
            { title: "Classical Waltz", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/classical_waltz.wav?raw=true", category: "Piano", duration: "1:10" },
            { title: "Fragments of a Forgotten Melody", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/fragments_of_a_forgotten_melody.wav?raw=true", category: "Piano", duration: "2:34" },
            { title: "Für Elise", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/fur_elise.wav?raw=true", category: "Piano", duration: "1:08" },
            { title: "Inspiring Piano", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/inspiring_piano.wav?raw=true", category: "Piano", duration: "2:27" },
            { title: "Malirec Studio Sad Piano", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/malirec_studio_sad_piano.wav?raw=true", category: "Piano", duration: "2:06" },
            { title: "Midnight in Montreux Jazz", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/midnight_in_montreux-jazz.wav?raw=true", category: "Piano", duration: "2:08" },
            { title: "Nocturn in the Moon's Embrace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/nocturn_in_the_moons_embrace.wav?raw=true", category: "Piano", duration: "2:54" },
            { title: "Sad and Emotional Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/sad_and_emotional_violin.wav?raw=true", category: "Piano", duration: "2:12" },
            { title: "Sad Piano Distant", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/sad_piano_distant.wav?raw=true", category: "Piano", duration: "1:20" },
            { title: "The Elegant Chill", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/piano/the_elegant_chill.wav?raw=true", category: "Piano", duration: "1:24" }
        ],
        "Violin and Cello": [
            { title: "Baroque Violin Concerto No 1", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/baroque_violin_concerto_no_1.wav?raw=true", category: "Violin and Cello", duration: "2:01" },
            { title: "Bright Violin and Cello", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/bright_violin_and_cello.wav?raw=true", category: "Violin and Cello", duration: "1:05" },
            { title: "Classical Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/classical_violin.wav?raw=true", category: "Violin and Cello", duration: "3:04" },
            { title: "Eitan EP Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/eitan_ep_violin.wav?raw=true", category: "Violin and Cello", duration: "2:07" },
            { title: "Elgar Cello Concerto", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/elgar_cello_concerto.wav?raw=true", category: "Violin and Cello", duration: "1:27" },
            { title: "Emotional Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/emotional_violin.wav?raw=true", category: "Violin and Cello", duration: "1:13" },
            { title: "Happy Cello & Violins", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/happy-cello_&_violins.wav?raw=true", category: "Violin and Cello", duration: "1:21" },
            { title: "Inspiring Cello Bach", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/inspiring_cello_bach.wav?raw=true", category: "Violin and Cello", duration: "2:45" },
            { title: "Modern Military Cellos & Violins", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/modern_military_cellos_&_violins.wav?raw=true", category: "Violin and Cello", duration: "1:11" },
            { title: "Positive Cello & Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/positive_cello_&_violin.wav?raw=true", category: "Violin and Cello", duration: "1:12" },
            { title: "Sad and Emotional Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/sad_and_emotional_violin.wav?raw=true", category: "Violin and Cello", duration: "2:12" },
            { title: "Sad Harp Violins", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/sad_harp_violins.wav?raw=true", category: "Violin and Cello", duration: "1:20" },
            { title: "Sad Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/sad_violin.wav?raw=true", category: "Violin and Cello", duration: "1:21" },
            { title: "Sad Violin 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/sad_violin_2.wav?raw=true", category: "Violin and Cello", duration: "1:52" },
            { title: "Schubert Sonata No 20", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/schubert_sonata_no_20.wav?raw=true", category: "Violin and Cello", duration: "0:53" },
            { title: "Sibelius Etude", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/sibelius_etude.wav?raw=true", category: "Violin and Cello", duration: "0:54" },
            { title: "Studio Kolomna", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/studio_kolomna.wav?raw=true", category: "Violin and Cello", duration: "0:57" },
            { title: "Violin Partita No 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/violin_partita_no_2.wav?raw=true", category: "Violin and Cello", duration: "2:14" },
            { title: "Violin Piano", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/violin_piano.wav?raw=true", category: "Violin and Cello", duration: "1:46" },
            { title: "Virtuos Violin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/violin_cello/virtuos_violin.wav?raw=true", category: "Violin and Cello", duration: "1:46" }
        ],
        "Orchestra": [
            { title: "19th Century Overture", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/19th_century_overture.wav?raw=true", category: "Orchestra", duration: "2:01" },
            { title: "Classic Piano Concerto (Orchestral)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/classic_piano_concerto_orchestral.wav?raw=true", category: "Orchestra", duration: "8:48" },
            { title: "Edward Elgar Cello Concerto", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/edward_elgar_cello_concerto.wav?raw=true", category: "Orchestra", duration: "1:27" },
            { title: "Epic Background Music", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/epic_background_music.wav?raw=true", category: "Orchestra", duration: "2:22" },
            { title: "Inspirational Symphony", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/inspirational_symphony.wav?raw=true", category: "Orchestra", duration: "2:06" },
            { title: "Patriotic Orchestra", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/orchestra/patriotic_orchestra.wav?raw=true", category: "Orchestra", duration: "5:23" }
        ],
        "Percussion": [
            { title: "Beat Down", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/beat_down.wav?raw=true", category: "Percussion", duration: "1:16" },
            { title: "Champions Blood", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/champions_blood.wav?raw=true", category: "Percussion", duration: "1:15" },
            { title: "Heart of the Ga...", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/heart_of_the_game.wav?raw=true", category: "Percussion", duration: "2:13" },
            { title: "Rally Cry", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/rally_cry.wav?raw=true", category: "Percussion", duration: "1:34" },
            { title: "Rhythm Rush", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/rhythm_rush.wav?raw=true", category: "Percussion", duration: "1:04" },
            { title: "The Final Push", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/the_final_push.wav?raw=true", category: "Percussion", duration: "1:17" },
            { title: "The Stampede", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/the_stampede.wav?raw=true", category: "Percussion", duration: "2:19" },
            { title: "Titan's March", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/drums/titans_march.wav?raw=true", category: "Percussion", duration: "1:14" }
        ],
        "Flutes": [
            { title: "Baroque Adagio Flutes", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/baroque_adagio_flutes.wav?raw=true", category: "Flutes", duration: "2:56" },
            { title: "Duet of Dreams", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/duet_of_dreams.mp3?raw=true", category: "Flutes", duration: "3:12" },
            { title: "Song of the Sacred River", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/song_of_the_sacred_river.wav?raw=true", category: "Flutes", duration: "2:26" },
            { title: "Song of the Zen Garden", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/song_of_the_zen_garden.wav?raw=true", category: "Flutes", duration: "2:17" },
            { title: "The Fairy's Lullaby", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/the_fairys_lullaby.wav?raw=true", category: "Flutes", duration: "2:16" },
            { title: "Whispers of the Wind", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/flutes/whispers_of_the_wind.wav?raw=true", category: "Flutes", duration: "2:28" }
        ],
        "Japanese": [
            { title: "Autumn's Embrace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/autumns_embrace.wav?raw=true", category: "Japanese", duration: "2:38" },
            { title: "Awakening of the Koi", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/awakening_of_the_koi.wav?raw=true", category: "Japanese", duration: "2:53" },
            { title: "Awakening of the Koi (Koto Only)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/awakening_of_the_koi_koto_only.wav?raw=true", category: "Japanese", duration: "2:53" },
            { title: "Echos of the Shimmering Moon", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/echos_of_the_shimmering_moon.wav?raw=true", category: "Japanese", duration: "2:22" },
            { title: "Honor Beyond Death", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/honor_beyond_death.wav?raw=true", category: "Japanese", duration: "2:25" },
            { title: "Honor Beyond Death (Koto Only)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/honor_beyond_death_koto_only.wav?raw=true", category: "Japanese", duration: "2:25" },
            { title: "Serenity of the Silent Temple", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/serenity_of_the_silent_temple.wav?raw=true", category: "Japanese", duration: "2:38" },
            { title: "Song of the Bamboo Grove", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/song_of_the_bamboo_grove.wav?raw=true", category: "Japanese", duration: "2:34" },
            { title: "Traditional Japan Koto (Fast)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/traditional_japan_koto_fast.wav?raw=true", category: "Japanese", duration: "2:28" },
            { title: "Traditional Japan Koto (Slow)", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/traditional_japan_koto_slow.wav?raw=true", category: "Japanese", duration: "1:49" },
            { title: "Tranquil Waters of the East", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/japanese/tranquil_waters_of_the_east.wav?raw=true", category: "Japanese", duration: "2:22" }
        ],
        "Accordion": [
            { title: "Bella Notte in Montmartre", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/accordion/bella_notte_in_montmartre.wav?raw=true", category: "Accordion", duration: "1:01" },
            { title: "Bubbles and Baguettes", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/accordion/bubbles_and_baguettes.wav?raw=true", category: "Accordion", duration: "1:01" },
            { title: "Paris", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/accordion/Paris.wav?raw=true", category: "Accordion", duration: "1:38" },
            { title: "V1", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/accordion/v1.wav?raw=true", category: "Accordion", duration: "1:11" }
        ],
        "Oregon": [
            { title: "Dracula's Castle", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/oregon/draculas_castle.wav?raw=true", category: "Oregon", duration: "0:59" }
        ],
        "Arabic": [
            { title: "Islamic", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/arabic/islamic.wav?raw=true", category: "Arabic", duration: "1:35" },
            { title: "Mid East Flute", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/arabic/mid_east_flute.wav?raw=true", category: "Arabic", duration: "2:59" },
            { title: "Mid East Flute Solo", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/arabic/mid_east_flute_solo.wav?raw=true", category: "Arabic", duration: "2:59" },
            { title: "Ramadan", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/arabic/ramadan.wav?raw=true", category: "Arabic", duration: "2:43" },
            { title: "The Arabian", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/arabic/the_arabian.wav?raw=true", category: "Arabic", duration: "2:06" }
        ],
        "Background Ambiance": [
            { title: "Meditation Bowls", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/meditation-bowls.wav?raw=true", category: "Background Ambiance", duration: "3:30" },
            { title: "Rain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/rain.wav?raw=true", category: "Background Ambiance", duration: "0:35" },
            { title: "Forest", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/forest.wav?raw=true", category: "Background Ambiance", duration: "2:06" },
            { title: "Waves", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/wave.wav?raw=true", category: "Background Ambiance", duration: "1:08" },
            { title: "Coffee Shop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/coffee-shop.wav?raw=true", category: "Background Ambiance", duration: "2:00" },
            { title: "White Noise", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/white-noise.wav?raw=true", category: "Background Ambiance", duration: "0:36" },
            { title: "Pink Noise", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/pink-noise.wav?raw=true", category: "Background Ambiance", duration: "1:00" },
            { title: "Brown Noise", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/brown-noise.wav?raw=true", category: "Background Ambiance", duration: "1:39" },
            { title: "Fan", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/fan.wav?raw=true", category: "Background Ambiance", duration: "1:00" },
            { title: "Thunderstorm", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/thunderstorm.wav?raw=true", category: "Background Ambiance", duration: "1:24" },
            { title: "River", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/river.wav?raw=true", category: "Background Ambiance", duration: "2:04" },
            { title: "Birds", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/birds.wav?raw=true", category: "Background Ambiance", duration: "1:16" },
            { title: "Fireplace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/fireplace.wav?raw=true", category: "Background Ambiance", duration: "2:01" },
            { title: "City", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/city.wav?raw=true", category: "Background Ambiance", duration: "1:33" },
            { title: "Wind", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/wind.wav?raw=true", category: "Background Ambiance", duration: "1:49" },
            { title: "Crickets", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/Crickets.wav?raw=true", category: "Background Ambiance", duration: "1:33" },
            { title: "Waterfall", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/waterfall.wav?raw=true", category: "Background Ambiance", duration: "0:43" },
            { title: "Library", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/library.wav?raw=true", category: "Background Ambiance", duration: "0:52" },
            { title: "Rain on Roof", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/rain-roof.wav?raw=true", category: "Background Ambiance", duration: "1:30" },
            { title: "Vinyl Crackle", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/backgroundambiance/vinyl_crackle.wav?raw=true", category: "Background Ambiance", duration: "0:11" }
        ],
        "Loops": [
            { title: "Ancient Athens Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/ancient_athens_loop.wav?raw=true", category: "Loops", duration: "3:23" },
            { title: "Ancient Summer Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/ancient_summer_Loop.wav?raw=true", category: "Loops", duration: "1:41" },
            { title: "Cafe Con Leche Beats Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/cafe_con_leche_beats_loop.wav?raw=true", category: "Loops", duration: "0:16" },
            { title: "Dawn in the Misty Pines Loop 1", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/dawn_in_the_misty_pine_loop_1.wav?raw=true", category: "Loops", duration: "0:22" },
            { title: "Dawn in the Misty Pines Loop 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/dawn_in_the_misty_pine_loop_2.wav?raw=true", category: "Loops", duration: "0:22" },
            { title: "Honey Drip Melodies Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/honey_drip_melodies_loop.wav?raw=true", category: "Loops", duration: "9:46" },
            { title: "Koi Pond Calculus Loop 1", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/koi_pond_calculus_loop_1.wav?raw=true", category: "Loops", duration: "0:21" },
            { title: "Koi Pond Calculus Loop 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/koi_pond_calculus_loop_2.wav?raw=true", category: "Loops", duration: "0:21" },
            { title: "Taxi Window Views Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/taxi_window_views_loop.wav?raw=true", category: "Loops", duration: "9:36" },
            { title: "The Blood-Stained Harp of Voran Loop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/the_blood-stained_harp_of_voran_loop.wav?raw=true", category: "Loops", duration: "1:25" },
            { title: "The Last Candle Burns Loop 1", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/the_last_candle_burns_loop_1.wav?raw=true", category: "Loops", duration: "2:50" },
            { title: "The Last Candle Burns Loop 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/tracks/loop/the_last_candle_burns_loop_2.wav?raw=true", category: "Loops", duration: "0:21" }
        ]
      };
