// Video Library - organized by category
const videoLibrary = {
  "Abstract": [
    { title: "Cat with Blue Eyes", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20Cat%20with%20Blue%20Eyes.mp4?raw=true" },
    { title: "Colorful Planet Ring", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20Colorful%20Planet%20Ring.mp4?raw=true" },
    { title: "DNA", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20DNA.mp4?raw=true" },
    { title: "Geometric Clock Red", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20Geometric%20Clock%20Red.mp4?raw=true" },
    { title: "Man with Colors", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20Man%20with%20Colors.mp4?raw=true" },
    { title: "Neurons", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20Neurons.mp4?raw=true" },
    { title: "White Lines on Blue Background", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Abstract%20-%20White%20Lines%20on%20Blue%20Background.mp4?raw=true" }
  ],
  "Anime & Characters": [
    { title: "Android", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Android.mp4?raw=true" },
    { title: "Anonymous - Freedom Phantom", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Anonymous%20-%20Freedom%20Phantom.mp4?raw=true" },
    { title: "Anonymous - Mask", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Anonymous%20-Mask.mp4?raw=true" },
    { title: "Art - Golden Masks", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Art%20-%20Golden%20Masks.mp4?raw=true" },
    { title: "Bongo Cat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Bongo%20Cat.mp4?raw=true" },
    { title: "Dual Katanas Miyamoto Musashi", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Dual%20Katanas%20Miyamoto%20Musash.mp4?raw=true" },
    { title: "Eyes - Elf", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Eyes%20-%20Elf.mp4?raw=true" },
    { title: "Eyes - Sakura", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Eyes%20-%20Sakura.mp4?raw=true" },
    { title: "Moonlit Ronin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Moonlit%20Roninx.mp4?raw=true" },
    { title: "Samurai - Magic Gauntlets", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Samarai%20-%20Magic%20gauntlets.mp4?raw=true" },
    { title: "Samurai Dragon Gate", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Samurai%20Dragon%20Gate.mp4?raw=true" },
    { title: "Samurai vs Assassin Moonlight", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Samurai%20vs%20Assassin%20Moonlight.mp4?raw=true" },
    { title: "Veil of Thorns", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Viel%20of%20Thorns.mp4?raw=true" }
  ],
  "Girl": [
    { title: "Crimson Butterfly Nightfall", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20%20-%20Crimson%20Butterfly%20Nightfallx.mp4?raw=true" },
    { title: "Daughter of the Eastern Sky", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20%20-%20Daughter%20of%20the%20Eastern%20Sky.mp4?raw=true" },
    { title: "Bioluminescent Beach", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Bioluminescent%20Beach.mp4?raw=true" },
    { title: "Carolina", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Carolina.mp4?raw=true" },
    { title: "Chisa Autumn Temple", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Chisa%20Autumn%20Templex.mp4?raw=true" },
    { title: "Chisa Shattered Reflections", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Chisa%20Shattered%20Reflections.mp4?raw=true" },
    { title: "Daughter of the Cyber Eclipse", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Daughter%20of%20the%20Cyber%20Eclipse.mp4?raw=true" },
    { title: "Dragonbound Silence", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Dragonbound%20Silence.mp4?raw=true" },
    { title: "Dream Chaser", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Dream%20Chaser.mp4?raw=true" },
    { title: "Fantasy Smoking Chilling", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Fantasy%20Smoking%20Chilling.mp4?raw=true" },
    { title: "Gamer", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Gamer.mp4?raw=true" },
    { title: "Games", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Games.mp4?raw=true" },
    { title: "Glitch", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Glitch.mp4?raw=true" },
    { title: "Glitch Queen Awakens", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Glitch%20Queen%20Awakens.mp4?raw=true" },
    { title: "Samurai Tattoo", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Samarai%20Tattoo.mp4?raw=true" },
    { title: "Shadowblade Warrior", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Shaddowblade%20Warrior.mp4?raw=true" },
    { title: "Smoking", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Smoking.mp4?raw=true" },
    { title: "Water", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Water.mp4?raw=true" },
    { title: "Whispering Eva", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Whispering%20Eva.mp4?raw=true" },
    { title: "Witch", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Witch.mp4?raw=true" },
    { title: "Wolf Demon", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-%20Wolf%20Demon.mp4?raw=true" },
    { title: "Emerald Code", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Girl%20-emerald%20code.mp4?raw=true" },
    { title: "Glitch Girl 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Glitch%20-%20Girl%202.mp4?raw=true" },
    { title: "Moon Girl", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Moon%20-%20Girl.mp4?raw=true" },
    { title: "Night Girl Stars", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Night%20-%20girl%20Starts.mp4?raw=true" },
    { title: "Two Girls Under Starlight", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Night%20-%20Two%20Girls%20Under%20Starlightx.mp4?raw=true" }
  ],
  "Cafe & Cozy": [
    { title: "Beach Cafe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cafe%20-%20Beach.mp4?raw=true" },
    { title: "Fall Cafe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cafe%20-%20Fall.mp4?raw=true" },
    { title: "Fall Season Cafe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cafe%20-%20Fall%20Season.mp4?raw=true" },
    { title: "Winter Snowfall Cafe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cafe%20-%20Winter%20Snowfall.mp4?raw=true" },
    { title: "Peaceful Campfire", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Campfire%20-%20Peaceful.mp4?raw=true" },
    { title: "Christmas Snowman", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Christmas%20-%20Snowman.mp4?raw=true" },
    { title: "Christmas Fireplace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Christmas%20Fireplacex.mp4?raw=true" },
    { title: "Christmas Room with Fireplace", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Christmas%20Room%20with%20Fireplacex.mp4?raw=true" },
    { title: "Halloween Pumpkin", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Halloween%20Pumpkin.mp4?raw=true" }
  ],
  "City & Cyberpunk": [
    { title: "City - Cyber", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Cyber.mp4?raw=true" },
    { title: "City - Detroit", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Detroit.mp4?raw=true" },
    { title: "City - Fireworks", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Fireworks.mp4?raw=true" },
    { title: "City - Horizon Day", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Horizon%20Day.mp4?raw=true" },
    { title: "City - Horizon Night", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Horizon%20night.mp4?raw=true" },
    { title: "City - Rainy View", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20-%20Rainy%20View.mp4?raw=true" },
    { title: "City of Pain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/City%20of%20Pain.mp4?raw=true" },
    { title: "Cityscape Silhouette", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cityscape%20Silhouette.mp4?raw=true" },
    { title: "Cyberpunk - Tokyo", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20-%20%20Tokyo.mp4?raw=true" },
    { title: "Cyberpunk - City Night", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20-%20City%20Night.mp4?raw=true" },
    { title: "Cyberpunk - Cityscape 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20-%20Cityscape%202.mp4?raw=true" },
    { title: "Cyberpunk City", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20City.mp4?raw=true" },
    { title: "Cyberpunk City - Emely", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20City%20-%20Emely.mp4?raw=true" },
    { title: "Cyberpunk City - Night", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20City%20-%20Night.mp4?raw=true" },
    { title: "Cyberpunk City 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20City%202.mp4?raw=true" },
    { title: "Cyberpunk Cityscape", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cyberpunk%20Cityscape.mp4?raw=true" },
    { title: "Night - City in the Mountains", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Night%20-%20City%20in%20the%20Mountains.mp4?raw=true" },
    { title: "Pixel - Cyberpunk Bar", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Pixel%20-%20Cyberpunk%20Bar.mp4?raw=true" },
    { title: "Pixel City", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Pixel%20City.mp4?raw=true" },
    { title: "Pixel City 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Pixel%20City%202.mp4?raw=true" }
  ],
  "Digital & Tech": [
    { title: "Blue Programming", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Digital%20-%20Blue%20Programming.mp4?raw=true" },
    { title: "Circuit Globe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Digital%20-%20Circuit%20Globe.mp4?raw=true" },
    { title: "Electronic Circuit", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Digital%20-%20Electronic%20Circuit.mp4?raw=true" },
    { title: "Digital Reaper", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Digital%20-%20Reaper.mp4?raw=true" },
    { title: "Digital Globe", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Digital%20Globe.mp4?raw=true" },
    { title: "Colorful Cube", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Colorful%20Cube.mp4?raw=true" },
    { title: "Hacker Desktop", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Hacker%20-%20Desktop.mp4?raw=true" },
    { title: "HUD - Elements", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/HUD%20-%20Elements.mp4?raw=true" },
    { title: "HUD - Space Science", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/HUD%20-%20Space%20Science.mp4?raw=true" },
    { title: "HUD - Tech", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/HUD%20-%20Tech.mp4?raw=true" },
    { title: "Matrix Code - Colorful", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Matrix%20Code%20-%20Colorful.mp4?raw=true" }
  ],
  "Landscape & Nature": [
    { title: "Cave Tree", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cave%20Tree.mp4?raw=true" },
    { title: "Forest - Whispering Lights", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Forest%20-%20Whispering%20Lights.mp4?raw=true" },
    { title: "Forgotten Gas Station", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Forgotten%20Gas%20Station.mp4?raw=true" },
    { title: "Horizon - Endless Water", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Horizon%20-%20Endless%20Water.mp4?raw=true" },
    { title: "Lake - Sunrise Over the Bayou", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Lake%20-%20Sunrise%20Over%20the%20Bayou.mp4?raw=true" },
    { title: "Apocalypse Hotel", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20Apocolypse%20hotel.mp4?raw=true" },
    { title: "Falls of the Forgotten Grove", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20falls%20of%20the%20forgotten%20grove.mp4?raw=true" },
    { title: "Floating Island", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20Floating%20Island.mp4?raw=true" },
    { title: "Neon Waterfall", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20Neon%20Waterfall.mp4?raw=true" },
    { title: "Ruins Beneath Red Leaves", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20Ruins%20Beneath%20Red%20Leaves.mp4?raw=true" },
    { title: "Tree of Eternal Night", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Landscape%20-%20Tree%20of%20Eternal%20Night.mp4?raw=true" },
    { title: "Northern Lights", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Northern%20Lights.mp4?raw=true" },
    { title: "Moonlight Lake", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Moonlight%20Lake.mp4?raw=true" },
    { title: "Night - Horizon Shooting Stars", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Night%20-%20Horizon%20Shooting%20Stars.mp4?raw=true" },
    { title: "Ocean - Bioluminescent", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Ocean%20-%20Bioluminescentt.mp4?raw=true" },
    { title: "Painting With Sharks", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Painting%20With%20Sharks.mp4?raw=true" },
    { title: "River - Sakura Purple House", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/River-%20Sakura%20Purple%20House.mp4?raw=true" }
  ],
  "Room & Lofi": [
    { title: "Lofi Girl with Cat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Lofi%20-%20Girl,%20with%20cat.mp4?raw=true" },
    { title: "Lofi Study Furry", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Lofi%20-%20Study%20Furry.mp4?raw=true" },
    { title: "Lofi Gaming", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Lowfi%20-%20Gaming.mp4?raw=true" },
    { title: "Room - Cyberpunk", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Cyberpunk.mp4?raw=true" },
    { title: "Room - Dystopia", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Dystopia.mp4?raw=true" },
    { title: "Room - Galaxy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Galaxy.mp4?raw=true" },
    { title: "Room - Green", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Green.mp4?raw=true" },
    { title: "Room - Hacker", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Hacker.mp4?raw=true" },
    { title: "Room - Mountain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Mountain.mp4?raw=true" },
    { title: "Room - Neon Galaxy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Neon%20Galaxy.mp4?raw=true" },
    { title: "Room - Orbital Planet", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Orbital%20Planet.mp4?raw=true" },
    { title: "Room - Rainy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Rainy.mp4?raw=true" },
    { title: "Room - Space Planet", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Space%20Planet.mp4?raw=true" },
    { title: "Room - Space Planet Horizon", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Space%20Planet%20Horizon.mp4?raw=true" },
    { title: "Room - Study Night Rain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Room%20-%20Study%20Night%20Rain.mp4?raw=true" },
    { title: "Beach House", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/vecteezy_a-house-on-the-beach-in-the-middle-of-the-sea-with-beautiful_47927730.mp4?raw=true" },
    { title: "Room with Aquarium", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/vecteezy_interior-of-the-room-with-aquarium-and-beautiful-view-in-the_46578703.mp4?raw=true" },
    { title: "Lofi Room with Clock", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/vecteezy_loop-animation-lofi-style-room-with-clock-and-window_45735090.mp4?raw=true" },
    { title: "Pixel Rain", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Pixel%20Rain.mp4?raw=true" }
  ],
  "Space & Cosmic": [
    { title: "Astronaut - Trippy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Astranaut%20-%20Trippy.mp4?raw=true" },
    { title: "Astronaut in the Ocean", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Astronaut%20in%20the%20Ocean.mp4?raw=true" },
    { title: "Cute UFO", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Cute%20UFO.mp4?raw=true" },
    { title: "Earth", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Earth.mp4?raw=true" },
    { title: "Inner Core", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Inner%20Core.mp4?raw=true" },
    { title: "Moon Cat", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Moon%20Cat.mp4?raw=true" },
    { title: "Quasar", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Quazar.mp4?raw=true" },
    { title: "Singularity - Colors of the Void", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Singularity%20-%20Colors%20of%20the%20Void.mp4?raw=true" },
    { title: "Singularity - Heart", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Singularity%20-%20heart.mp4?raw=true" },
    { title: "Space", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Space.mp4?raw=true" },
    { title: "Space - Nebula", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Space%20-%20Nebula.mp4?raw=true" },
    { title: "Space - Planet in a Galaxy", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Space%20-%20Planet%20in%20a%20galaxy.mp4?raw=true" },
    { title: "Space - Swirling Nebula", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Space%20-%20Swirling%20Nebula.mp4?raw=true" },
    { title: "Space 2", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Space%202.mp4?raw=true" }
  ],
  "Temple & Mystic": [
    { title: "Dark - Snowfall Exit", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Dark%20-%20Snowfall%20Exit.mp4?raw=true" },
    { title: "Meditation", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Meditiation.mp4?raw=true" },
    { title: "Temple - Gate", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Temple%20-%20gate.mp4?raw=true" },
    { title: "Temple - Hidden Temple", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Temple%20-%20Hidden%20Temple.mp4?raw=true" },
    { title: "Temple - Ruins in Winter", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Temple%20-%20Ruions%20in%20Winter.mp4?raw=true" },
    { title: "Yin and Yang", src: "https://media.githubusercontent.com/media/DrTHunter/AudioOasis/refs/heads/main/Video%20Files/Yin%20and%20yang.mp4?raw=true" }
  ]
};
