// Video Library - organized by category
const videoLibrary = {
  "Abstract": [
    { title: "Cat with Blue Eyes", src: "Video Files/Abstract - Cat with Blue Eyes.mp4" },
    { title: "Colorful Planet Ring", src: "Video Files/Abstract - Colorful Planet Ring.mp4" },
    { title: "DNA", src: "Video Files/Abstract - DNA.mp4" },
    { title: "Geometric Clock Red", src: "Video Files/Abstract - Geometric Clock Red.mp4" },
    { title: "Man with Colors", src: "Video Files/Abstract - Man with Colors.mp4" },
    { title: "Neurons", src: "Video Files/Abstract - Neurons.mp4" },
    { title: "White Lines on Blue Background", src: "Video Files/Abstract - White Lines on Blue Background.mp4" }
  ],
  "Anime & Characters": [
    { title: "Android", src: "Video Files/Android.mp4" },
    { title: "Anonymous - Freedom Phantom", src: "Video Files/Anonymous - Freedom Phantom.mp4" },
    { title: "Anonymous - Mask", src: "Video Files/Anonymous -Mask.mp4" },
    { title: "Art - Golden Masks", src: "Video Files/Art - Golden Masks.mp4" },
    { title: "Bongo Cat", src: "Video Files/Bongo Cat.mp4" },
    { title: "Dual Katanas Miyamoto Musashi", src: "Video Files/Dual Katanas Miyamoto Musash.mp4" },
    { title: "Eyes - Elf", src: "Video Files/Eyes - Elf.mp4" },
    { title: "Eyes - Sakura", src: "Video Files/Eyes - Sakura.mp4" },
    { title: "Moonlit Ronin", src: "Video Files/Moonlit Roninx.mp4" },
    { title: "Samurai - Magic Gauntlets", src: "Video Files/Samarai - Magic gauntlets.mp4" },
    { title: "Samurai Dragon Gate", src: "Video Files/Samurai Dragon Gate.mp4" },
    { title: "Samurai vs Assassin Moonlight", src: "Video Files/Samurai vs Assassin Moonlight.mp4" },
    { title: "Veil of Thorns", src: "Video Files/Viel of Thorns.mp4" }
  ],
  "Girl": [
    { title: "Crimson Butterfly Nightfall", src: "Video Files/Girl  - Crimson Butterfly Nightfallx.mp4" },
    { title: "Daughter of the Eastern Sky", src: "Video Files/Girl  - Daughter of the Eastern Sky.mp4" },
    { title: "Bioluminescent Beach", src: "Video Files/Girl - Bioluminescent Beach.mp4" },
    { title: "Carolina", src: "Video Files/Girl - Carolina.mp4" },
    { title: "Chisa Autumn Temple", src: "Video Files/Girl - Chisa Autumn Templex.mp4" },
    { title: "Chisa Shattered Reflections", src: "Video Files/Girl - Chisa Shattered Reflections.mp4" },
    { title: "Daughter of the Cyber Eclipse", src: "Video Files/Girl - Daughter of the Cyber Eclipse.mp4" },
    { title: "Dragonbound Silence", src: "Video Files/Girl - Dragonbound Silence.mp4" },
    { title: "Dream Chaser", src: "Video Files/Girl - Dream Chaser.mp4" },
    { title: "Fantasy Smoking Chilling", src: "Video Files/Girl - Fantasy Smoking Chilling.mp4" },
    { title: "Gamer", src: "Video Files/Girl - Gamer.mp4" },
    { title: "Games", src: "Video Files/Girl - Games.mp4" },
    { title: "Glitch", src: "Video Files/Girl - Glitch.mp4" },
    { title: "Glitch Queen Awakens", src: "Video Files/Girl - Glitch Queen Awakens.mp4" },
    { title: "Samurai Tattoo", src: "Video Files/Girl - Samarai Tattoo.mp4" },
    { title: "Shadowblade Warrior", src: "Video Files/Girl - Shaddowblade Warrior.mp4" },
    { title: "Smoking", src: "Video Files/Girl - Smoking.mp4" },
    { title: "Water", src: "Video Files/Girl - Water.mp4" },
    { title: "Whispering Eva", src: "Video Files/Girl - Whispering Eva.mp4" },
    { title: "Witch", src: "Video Files/Girl - Witch.mp4" },
    { title: "Wolf Demon", src: "Video Files/Girl - Wolf Demon.mp4" },
    { title: "Emerald Code", src: "Video Files/Girl -emerald code.mp4" },
    { title: "Glitch Girl 2", src: "Video Files/Glitch - Girl 2.mp4" },
    { title: "Moon Girl", src: "Video Files/Moon - Girl.mp4" },
    { title: "Night Girl Stars", src: "Video Files/Night - girl Starts.mp4" },
    { title: "Two Girls Under Starlight", src: "Video Files/Night - Two Girls Under Starlightx.mp4" }
  ],
  "Cafe & Cozy": [
    { title: "Beach Cafe", src: "Video Files/Cafe - Beach.mp4" },
    { title: "Fall Cafe", src: "Video Files/Cafe - Fall.mp4" },
    { title: "Fall Season Cafe", src: "Video Files/Cafe - Fall Season.mp4" },
    { title: "Winter Snowfall Cafe", src: "Video Files/Cafe - Winter Snowfall.mp4" },
    { title: "Peaceful Campfire", src: "Video Files/Campfire - Peaceful.mp4" },
    { title: "Christmas Snowman", src: "Video Files/Christmas - Snowman.mp4" },
    { title: "Christmas Fireplace", src: "Video Files/Christmas Fireplacex.mp4" },
    { title: "Christmas Room with Fireplace", src: "Video Files/Christmas Room with Fireplacex.mp4" },
    { title: "Halloween Pumpkin", src: "Video Files/Halloween Pumpkin.mp4" }
  ],
  "City & Cyberpunk": [
    { title: "City - Cyber", src: "Video Files/City - Cyber.mp4" },
    { title: "City - Detroit", src: "Video Files/City - Detroit.mp4" },
    { title: "City - Fireworks", src: "Video Files/City - Fireworks.mp4" },
    { title: "City - Horizon Day", src: "Video Files/City - Horizon Day.mp4" },
    { title: "City - Horizon Night", src: "Video Files/City - Horizon night.mp4" },
    { title: "City - Rainy View", src: "Video Files/City - Rainy View.mp4" },
    { title: "City of Pain", src: "Video Files/City of Pain.mp4" },
    { title: "Cityscape Silhouette", src: "Video Files/Cityscape Silhouette.mp4" },
    { title: "Cyberpunk - Tokyo", src: "Video Files/Cyberpunk -  Tokyo.mp4" },
    { title: "Cyberpunk - City Night", src: "Video Files/Cyberpunk - City Night.mp4" },
    { title: "Cyberpunk - Cityscape 2", src: "Video Files/Cyberpunk - Cityscape 2.mp4" },
    { title: "Cyberpunk City", src: "Video Files/Cyberpunk City.mp4" },
    { title: "Cyberpunk City - Emely", src: "Video Files/Cyberpunk City - Emely.mp4" },
    { title: "Cyberpunk City - Night", src: "Video Files/Cyberpunk City - Night.mp4" },
    { title: "Cyberpunk City 2", src: "Video Files/Cyberpunk City 2.mp4" },
    { title: "Cyberpunk Cityscape", src: "Video Files/Cyberpunk Cityscape.mp4" },
    { title: "Night - City in the Mountains", src: "Video Files/Night - City in the Mountains.mp4" },
    { title: "Pixel - Cyberpunk Bar", src: "Video Files/Pixel - Cyberpunk Bar.mp4" },
    { title: "Pixel City", src: "Video Files/Pixel City.mp4" },
    { title: "Pixel City 2", src: "Video Files/Pixel City 2.mp4" }
  ],
  "Digital & Tech": [
    { title: "Blue Programming", src: "Video Files/Digital - Blue Programming.mp4" },
    { title: "Circuit Globe", src: "Video Files/Digital - Circuit Globe.mp4" },
    { title: "Electronic Circuit", src: "Video Files/Digital - Electronic Circuit.mp4" },
    { title: "Digital Reaper", src: "Video Files/Digital - Reaper.mp4" },
    { title: "Digital Globe", src: "Video Files/Digital Globe.mp4" },
    { title: "Colorful Cube", src: "Video Files/Colorful Cube.mp4" },
    { title: "Hacker Desktop", src: "Video Files/Hacker - Desktop.mp4" },
    { title: "HUD - Elements", src: "Video Files/HUD - Elements.mp4" },
    { title: "HUD - Space Science", src: "Video Files/HUD - Space Science.mp4" },
    { title: "HUD - Tech", src: "Video Files/HUD - Tech.mp4" },
    { title: "Matrix Code - Colorful", src: "Video Files/Matrix Code - Colorful.mp4" }
  ],
  "Landscape & Nature": [
    { title: "Cave Tree", src: "Video Files/Cave Tree.mp4" },
    { title: "Forest - Whispering Lights", src: "Video Files/Forest - Whispering Lights.mp4" },
    { title: "Forgotten Gas Station", src: "Video Files/Forgotten Gas Station.mp4" },
    { title: "Horizon - Endless Water", src: "Video Files/Horizon - Endless Water.mp4" },
    { title: "Lake - Sunrise Over the Bayou", src: "Video Files/Lake - Sunrise Over the Bayou.mp4" },
    { title: "Apocalypse Hotel", src: "Video Files/Landscape - Apocolypse hotel.mp4" },
    { title: "Falls of the Forgotten Grove", src: "Video Files/Landscape - falls of the forgotten grove.mp4" },
    { title: "Floating Island", src: "Video Files/Landscape - Floating Island.mp4" },
    { title: "Neon Waterfall", src: "Video Files/Landscape - Neon Waterfall.mp4" },
    { title: "Ruins Beneath Red Leaves", src: "Video Files/Landscape - Ruins Beneath Red Leaves.mp4" },
    { title: "Tree of Eternal Night", src: "Video Files/Landscape - Tree of Eternal Night.mp4" },
    { title: "Northern Lights", src: "Video Files/Northern Lights.mp4" },
    { title: "Moonlight Lake", src: "Video Files/Moonlight Lake.mp4" },
    { title: "Night - Horizon Shooting Stars", src: "Video Files/Night - Horizon Shooting Stars.mp4" },
    { title: "Ocean - Bioluminescent", src: "Video Files/Ocean - Bioluminescentt.mp4" },
    { title: "Painting With Sharks", src: "Video Files/Painting With Sharks.mp4" },
    { title: "River - Sakura Purple House", src: "Video Files/River- Sakura Purple House.mp4" }
  ],
  "Room & Lofi": [
    { title: "Lofi Girl with Cat", src: "Video Files/Lofi - Girl, with cat.mp4" },
    { title: "Lofi Study Furry", src: "Video Files/Lofi - Study Furry.mp4" },
    { title: "Lofi Gaming", src: "Video Files/Lowfi - Gaming.mp4" },
    { title: "Room - Cyberpunk", src: "Video Files/Room - Cyberpunk.mp4" },
    { title: "Room - Dystopia", src: "Video Files/Room - Dystopia.mp4" },
    { title: "Room - Galaxy", src: "Video Files/Room - Galaxy.mp4" },
    { title: "Room - Green", src: "Video Files/Room - Green.mp4" },
    { title: "Room - Hacker", src: "Video Files/Room - Hacker.mp4" },
    { title: "Room - Mountain", src: "Video Files/Room - Mountain.mp4" },
    { title: "Room - Neon Galaxy", src: "Video Files/Room - Neon Galaxy.mp4" },
    { title: "Room - Orbital Planet", src: "Video Files/Room - Orbital Planet.mp4" },
    { title: "Room - Rainy", src: "Video Files/Room - Rainy.mp4" },
    { title: "Room - Space Planet", src: "Video Files/Room - Space Planet.mp4" },
    { title: "Room - Space Planet Horizon", src: "Video Files/Room - Space Planet Horizon.mp4" },
    { title: "Room - Study Night Rain", src: "Video Files/Room - Study Night Rain.mp4" },
    { title: "Beach House", src: "Video Files/vecteezy_a-house-on-the-beach-in-the-middle-of-the-sea-with-beautiful_47927730.mp4" },
    { title: "Room with Aquarium", src: "Video Files/vecteezy_interior-of-the-room-with-aquarium-and-beautiful-view-in-the_46578703.mp4" },
    { title: "Lofi Room with Clock", src: "Video Files/vecteezy_loop-animation-lofi-style-room-with-clock-and-window_45735090.mp4" },
    { title: "Pixel Rain", src: "Video Files/Pixel Rain.mp4" }
  ],
  "Space & Cosmic": [
    { title: "Astronaut - Trippy", src: "Video Files/Astranaut - Trippy.mp4" },
    { title: "Astronaut in the Ocean", src: "Video Files/Astronaut in the Ocean.mp4" },
    { title: "Cute UFO", src: "Video Files/Cute UFO.mp4" },
    { title: "Earth", src: "Video Files/Earth.mp4" },
    { title: "Inner Core", src: "Video Files/Inner Core.mp4" },
    { title: "Moon Cat", src: "Video Files/Moon Cat.mp4" },
    { title: "Quasar", src: "Video Files/Quazar.mp4" },
    { title: "Singularity - Colors of the Void", src: "Video Files/Singularity - Colors of the Void.mp4" },
    { title: "Singularity - Heart", src: "Video Files/Singularity - heart.mp4" },
    { title: "Space", src: "Video Files/Space.mp4" },
    { title: "Space - Nebula", src: "Video Files/Space - Nebula.mp4" },
    { title: "Space - Planet in a Galaxy", src: "Video Files/Space - Planet in a galaxy.mp4" },
    { title: "Space - Swirling Nebula", src: "Video Files/Space - Swirling Nebula.mp4" },
    { title: "Space 2", src: "Video Files/Space 2.mp4" }
  ],
  "Temple & Mystic": [
    { title: "Dark - Snowfall Exit", src: "Video Files/Dark - Snowfall Exit.mp4" },
    { title: "Meditation", src: "Video Files/Meditiation.mp4" },
    { title: "Temple - Gate", src: "Video Files/Temple - gate.mp4" },
    { title: "Temple - Hidden Temple", src: "Video Files/Temple - Hidden Temple.mp4" },
    { title: "Temple - Ruins in Winter", src: "Video Files/Temple - Ruions in Winter.mp4" },
    { title: "Yin and Yang", src: "Video Files/Yin and yang.mp4" }
  ]
};
